### ISSUE TITLE
How to add new collections to this?

### ISSUE THREAD

**Issue by aminviral2006** [tutsplus/build-complete-website-expressjs#4]
How to add new collections to this?
or this is designed to work with only 1 collection?
thank you

**Comment by tyleryoungblood** [comment]
You need to log into the admin panel. 

Assuming going to localhost:3000 is properly taking you to the local copy of your application, go to http://localhost:3000/admin to log into the admin panel. 

username: admin
pass: admin

Then you can create new posts (which will create a new collection in your mongo database).
